version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - funcorder
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    varnamelen:
      ignore-names:
        - c
        - i
        - v
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    paths:
      - _test.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
